### ISSUE TITLE
not working/tests not passing on google cloud VM f1-micro but passes on travis-CI environment

### ISSUE THREAD

**Issue by DrPaulBrewer** [DrPaulBrewer/vaporlock#1]
This is a new issue as it was working on the same VM a few months ago.  

Test result from google f1-micro VM after adding should and mocha

and changing the bucket name for testing.

The bucket name chosen exists, and is readable, writable, listable from the google f1-micro VM
environment.

```
  vaporlock
    1) should only show 1 winner with 2 concurrent
    2) should only show 1 winner with 5 concurrent
    3) should only show 1 winner with 10 concurrent
    4) should only show 1 winner with 2 concurrent, unreleased lock
    ✓ should not show any locks because the old lock is unreleased
    ✓ wait 1 minute + 10 seconds  (70071ms)
    5) should only show 1 winner with 10 concurrently attempting override of expired lock
  2 passing (2m)
  5 failing
  1) vaporlock should only show 1 winner with 2 concurrent:
     Error: expected 1 locks, obtained: 0
      at test/index.js:34:29
  2) vaporlock should only show 1 winner with 5 concurrent:
     Error: expected 1 locks, obtained: 0
      at test/index.js:34:29
  3) vaporlock should only show 1 winner with 10 concurrent:
     Error: expected 1 locks, obtained: 0
      at test/index.js:34:29
  4) vaporlock should only show 1 winner with 2 concurrent, unreleased lock:
     Error: expected 1 locks, obtained: 0
      at test/index.js:34:29
  5) vaporlock should only show 1 winner with 10 concurrently attempting override of expired lock:
     Error: expected 1 locks, obtained: 0
      at test/index.js:34:29
npm ERR! Test failed.  See above for more details.
```

**Comment by DrPaulBrewer** [comment]
This was a test configuration issue.

In file `./test/index.js` to test on Google infrastructure, the storage initialization should be done with
no parameters.  Instead, the test -- configured for Travis-CI -- looks for a credentials file.  This file will not
exist in the Google Cloud environment and thus cause errors.

```
 vaporlock
    ✓ should only show 1 winner with 2 concurrent (11056ms)
    ✓ should only show 1 winner with 5 concurrent (11571ms)
    ✓ should only show 1 winner with 10 concurrent (13826ms)
    ✓ should only show 1 winner with 2 concurrent, unreleased lock (10444ms)
    ✓ should not show any locks because the old lock is unreleased
    ✓ wait 1 minute + 10 seconds  (70058ms)
    ✓ should only show 1 winner with 10 concurrently attempting override of expired lock (14334ms)
  7 passing (2m)

```
